data: 'jkp'
dtype: 'float32'
size_list: ['mega', 'large', 'small', 'micro']
window: 360
z_list:
- 1.0e-4
- 1.0e-3
- 1.0e-2
- 1.0e-1
- 1.0

num_tree: 100
sample_frac: 0.8
random_state: 42
n_jobs: 8

factors: 'all'
train: 'roll'
split:
  train: ['1963-01-31', '1987-12-31']
  test:  ['1988-01-31', '2024-12-31']