data: 'jkp'
dtype: 'float32'
size_list: ['all']
window: 360
max_depth_list: [3]
min_leaf_size: 12
bin: 10
z_list:
- 0

num_tree_list: [64]
sample_frac: 0.8
max_features: 3
random_state: 42
save: True
n_jobs: 8
parallel: "processes"

factors: ['market_equity', 'be_me', 'ope_be', 'at_gr1', 'ret_12_1']
train: 'roll'
split:
  train: ['1963-01-31', '1987-12-31']
  test:  ['1988-01-31', '2024-12-31']